import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
      <header className="bg-blue-600 text-white p-4">
      <h1 className="text-xl font-bold">CareerCompass</h1>
    </header>
       {children}
        <footer className="bg-gray-800 text-gray-300 py-6">
        <div className="container mx-auto px-6 text-center">
          <p>
            © {new Date().getFullYear()} CareerCompass. All rights reserved.
          </p>
          <p className="text-sm mt-2">
            Contact: info@careercompass.com | +91 234567
          </p>
        </div>
      </footer>
      </body>
    </html>
  );
}
